// <auto-generated />
namespace PMSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_bindings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_bindings));
        
        string IMigrationMetadata.Id
        {
            get { return "201705312143320_added_bindings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
